apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-dashboard
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubernetes-dashboard
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/kubernetes-dashboard
    repoURL: https://github.com/kubernetes/dashboard
    targetRevision: kubernetes-dashboard-7.10.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true