apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: magnolia
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: magnolia
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-chart
    repoURL: https://github.com/magnolia-sre/magnolia-docker
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true